### ISSUE TITLE
a ANSI -> an ANSI

### ISSUE THREAD

**Issue by apotheon** [rubyworks/vclog#11]
Conventions of English grammar suggest that all instances of " a ANSI " should be changed to " an ANSI " in the README file.

**Comment by trans** [comment]
Makes sense. But I did not find any cases of it in the README. I searched the whole project with grep and found one in bbcode.rb. So that's fixed.

**Comment by apotheon** [comment]
Unless there's something wrong with my view of the file, there are two instances, I believe:

"The default output is a ANSI colored GNU-like changelog."

"Again the default format is a ANSI colored GNU-like text style."

Let me know if you would like me to just submit a pull request.

**Comment by trans** [comment]
Sigh...it's late here. Yes, I was looking in the wrong project. Thanks.

**Comment by apotheon** [comment]
My pleasure.  I'm impressed by the prolific rate of rubyworks releases, and have felt an urge to make minor contributions that would be difficult to screw up (because it's late here, too).  I'm sure I'll be back for more later.
