### ISSUE TITLE
Commit Message Heuristics

### ISSUE THREAD

**Issue by ghost** [rubyworks/vclog#2]
Develop some commit message heuristics to determine if a commit is major, minor, bug, etc. Currently we use a type label --a trailing "[name]". This is okay, but often it is forgotten.

Also, a commit message could have multiple entry types. Should we try to handle this, or require the developer to commit each type separately? Is that a good practice? If we do handle multiple labels per commit, that would heavily change History output, as it would mens sub-dividing commit messages.

**Comment by ghost** [comment]
Note that as of version 1.3, the label can be put at the front, and it can simply be a word followed by a colon. This seems to be a kind of standard among some projects to identify the subsystem the commit effects --which is another reasonable way to categorize commits.

**Comment by trans** [comment]
Heuristics are now implemented (and are awesome!)
